# Generated by Django 4.0.2 on 2023-03-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio_pic', models.URLField()),
                ('bio_text', models.TextField()),
                ('bio_url', models.URLField()),
                ('featured', models.BooleanField()),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
