# Generated by Django 4.0.2 on 2023-03-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_categories_customuser_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='categories',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_categories',
            field=models.ManyToManyField(related_name='user_categories', to='users.Category'),
        ),
    ]
