# Generated by Django 4.0.2 on 2023-03-25 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_categories',
            new_name='categories',
        ),
    ]
