# Generated by Django 4.0.2 on 2023-03-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='users.Question'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='users.Category'),
        ),
    ]
