# Generated by Django 4.0.2 on 2023-03-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_questions_alter_customuser_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='questions',
            field=models.ManyToManyField(related_name='answers', to='users.Question'),
        ),
    ]
