# Generated by Django 4.0.2 on 2023-03-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='questions',
        ),
        migrations.AddField(
            model_name='customuser',
            name='question_answers',
            field=models.ManyToManyField(related_name='question_answers', to='users.Question'),
        ),
    ]
