# Generated by Django 4.0.2 on 2023-03-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_answer_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='questions',
            new_name='answers',
        ),
    ]
