# Generated by Django 4.0.2 on 2023-03-26 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_answers_remove_useranswer_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='questions',
            field=models.ManyToManyField(through='users.User_Answers', to='users.Questions'),
        ),
        migrations.AlterField(
            model_name='user_answers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
