# Generated by Django 4.0.2 on 2023-03-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_answers_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
