# Generated by Django 4.0.2 on 2023-04-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_customuser_blog_customuser_city_customuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
