# Generated by Django 4.0.2 on 2023-04-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_customuser_blog_alter_customuser_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='users.Category'),
        ),
    ]
