# Generated by Django 4.0.2 on 2023-04-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_answer_answer_alter_customuser_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='users.Category'),
        ),
    ]
