# Generated by Django 4.0.2 on 2023-04-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_customuser_blog_alter_customuser_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pronouns',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
